### ISSUE TITLE
Download links are broken

### ISSUE THREAD

**Issue by ramtinsoltani** [culturespy/umod#50]
All download links in the [wiki](https://github.com/culturespy/umod/wiki/Downloads) give 404 on Dropbox.

**Comment by culturespy** [comment]
Ok, this is what I get for not logging in here for like... _years_.

I still have all of the files related to this. I'll find some other way to host them. Sorry for the inconvenience.

Also, if someone is trying to revive this project or something, be my guest! I only exported it because I found the program useful and didn't want to see the code vanish.

**Comment by culturespy** [comment]
Should be fixed now. Enjoy. LMK if any problems.
